SHELL := /bin/bash

UV ?= uv
UV_DEFAULT_INDEX ?= https://pypi.org/simple
UV_RUN := $(UV) run --default-index $(UV_DEFAULT_INDEX)
PYTEST := $(UV_RUN) pytest

.PHONY: help setup skills report report-check test-python test-hpc test-rust \
	test-protocol test-report test-verifier test-promotion test

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "%-16s %s\n", $$1, $$2}'

setup: ## Create the Python 3.11 environment with uv
	@command -v $(UV) >/dev/null 2>&1 || { echo "uv is required"; exit 1; }
	$(UV) sync --default-index $(UV_DEFAULT_INDEX) --python 3.11.13 --dev

skills: ## Validate the vendored local Ion skills
	@command -v ion >/dev/null 2>&1 || { echo "Ion is required"; exit 1; }
	ion --json validate

report: ## Regenerate the offline HTML and Markdown deliverable
	$(UV_RUN) python scripts/build-report.py \
		--source reports/data/project.json \
		--repo-root .

report-check: ## Validate report schema, claims, links, and generated bytes
	$(UV_RUN) python scripts/check-deliverable.py \
		--source reports/data/project.json \
		--repo-root .

test-python: ## Run protocol and autoresearch unit tests
	$(PYTEST) -q \
		research/test_check_gate.py \
		research/test_care_bdd_design.py \
		autoresearch/test_autoresearch_protocol.py

test-hpc: ## Test bounded-run and Slurm adapters without touching a cluster
	$(PYTEST) -q \
		autoresearch/test_run_experiment.py \
		autoresearch/test_materialize_slurm_failures.py \
		scripts/tests/test_cluster_profile.py \
		scripts/tests/test_cluster_guardrail.py \
		scripts/tests/test_cluster_probe.py \
		scripts/tests/test_harness_slurm.py

test-rust: ## Run the locked Rust BDD/SAT/XAG test suite
	cargo fmt --all -- --check
	cargo test --locked --all-features --release

test-protocol: ## Check the frozen public protocol gate
	$(UV_RUN) python research/check_gate.py --phase protocol

test-report: ## Test deterministic report generation and validation
	$(PYTEST) -q \
		scripts/tests/test_report_model.py \
		scripts/tests/test_build_report.py \
		scripts/tests/test_check_deliverable.py

test-verifier: ## Test Julia wrapper and immutable verification records
	sh -n scripts/verify-julia.sh
	$(PYTEST) -q \
		scripts/tests/test_verify_julia.py \
		scripts/tests/test_record_verification.py

test-promotion: ## Test evidence-track promotion decisions
	$(PYTEST) -q scripts/tests/test_check_promotion.py

test: test-python test-hpc test-rust test-protocol test-report test-verifier test-promotion report-check ## Run the complete local baseline
